### ISSUE TITLE
Npm run start failled

### ISSUE THREAD

**Issue by papsrowan** [papsrowan/mobile-christ-tv#1]
I've try to rerun this project with yarn, i deleted the package-lock.json and I ran `yarn` but it didn't work. I've tried to run npm i after and the project crash always and always. please help

**Comment by BrightkyEfoo** [comment]
Retrive the commit where the project was already working well and take it. In future don't try again to use multiple package managers

**Comment by papsrowan** [comment]
> Retrive the commit where the project was already working well and take it. In future don't try again to use multiple package managers

Are you sure

**Comment by BrightkyEfoo** [comment]
Yes try it

> > Retrive the commit where the project was already working well and take it. In future don't try again to use multiple package managers
> 
> Are you sure
